site_name: REALM
site_url: https://G1rmmr.github.io/

theme:
  name: simple-blog
  theme_style: dark
  logo: img/logo.png
  favicon: img/logo.png
  components:
    title: false

nav:
  - Intro: index.md
  - Posts:
      - MIR 1.0: posts/2024-12-12.md
      - White Ashes: posts/2025-1-22.md
      - MIR 2.0: posts/2025-12-8.md

markdown_extensions:
  - admonition
