[project]
site_name = "R E A L M"
site_description = "Welcome to my place."
site_author = "John Nam"

copyright = """
Copyright &copy; 2025 John Nam
"""

docs_dir = "docs"
site_dir = "site"

extra_css = ["stylesheets/extra.css"]

nav = [
  {"H O M E" = "index.md"},
  {"P O S T" = [
    "posts/2025-12-8.md",
    "posts/2025-1-22.md",
    "posts/2024-12-12.md",
  ]}
]

[project.theme]
variant = "modern"
favicon = "img/favicon.png"
language = "ko"

[project.theme.palette]
scheme = "slate"
primary = "custom"

features = [
    "announce.dismiss",
    "content.action.edit",
    "content.action.view",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "header.autohide",
    "navigation.expand",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant.prefetch",
    "navigation.path",
    "navigation.prune",
    "navigation.sections",
    "navigation.tabs",
    "navigation.tracking",
    "search.highlight",
    "toc.integrate",
]