[project]
site_name = "R E A L M"
site_description = "Welcome to my place."
site_author = "John Nam"

copyright = "&copy; 2025 John Nam"

docs_dir = "docs"
site_dir = "site"

extra_css = ["stylesheets/extra.css"]

nav = [
  {"H O M E" = "index.md"},
  {"P O S T" = [
    "posts/2025-12-8.md",
    "posts/2025-1-22.md",
    "posts/2024-12-12.md",
  ]}
]

[project.theme]
variant = "modern"
favicon = "img/favicon.png"
language = "en"
logo = "img/favicon.png"

features = [
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.instant.progress",
    "navigation.tabs",
    "navigation.prune",
    "header.autohide",
    "announce.dismiss",
    "toc.integrate",
]

[project.theme.palette]
scheme = "slate"
primary = "custom"

[project.extra]
generator = false
