[project]
site_name = "R E A L M"
site_description = "Welcome to my place."
site_author = "John Nam"

copyright = """
Copyright &copy; 2025 John Nam
"""

docs_dir = "en/docs"
site_dir = "site/en"

extra_css = ["stylesheets/extra.css"]

nav = [
  {"Home" = "index.md"},
  {"Posts" = [
    "posts/2025-12-8.md",
    "posts/2025-1-22.md",
    "posts/2024-12-12.md",
  ]}
]

[project.theme]
variant = "modern"
favicon = "img/favicon.png"
language = "en"

[project.theme.palette]
scheme = "slate"
primary = "custom"

[project.extra]
alternate = [
  { name = "한국어", link = "/", lang = "ko" },
  { name = "English", link = "/en/", lang = "en" },
]

features = [
    "announce.dismiss",
    "content.action.edit",
    "content.action.view",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "header.autohide",
    "navigation.expand",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant.prefetch",
    "navigation.path",
    "navigation.prune",
    "navigation.sections",
    "navigation.tabs",
    "navigation.tracking",
    "search.highlight",
    "toc.integrate",
]
